spring.application.name=employee-management

# ===============================
# DATABASE (Railway MySQL)
# ===============================

spring.datasource.url=jdbc:mysql://yamanote.proxy.rlwy.net:49742/railway
spring.datasource.username=root
spring.datasource.password=mjzrxkQxgNUFOkPZogQKfyJqHCxFqBss

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Có thể xóa dòng dialect vì Hibernate tự nhận
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER PORT (QUAN TRỌNG CHO RENDER)
# ===============================

server.port=${PORT:8081}